import sqlite3
from Conexion import con,cur

def InicializaccioDb():
    cur.execute("PRAGMA foreign_keys = 1")
    Tipo=[(1, "Ropa", "Talla", "Material", "Color"),
    (2, "Bolsa", "Modelo", "Material", "Tamaño"),
    (3, "Perfume", "Aroma", "Volumen", "Concentración"),
    (4, "Accesorios", "Material", "Tipo", "Ajuste"),
    (5, "Calzado", "Número", "Tipo", "Color"),
    (6, "Labial", "Tono", "Efecto", "Marca"),
    (7, "Maquillaje", "Tono", "Zona", "Duración"),
    (8, "Cuidado Pelo", "Tipo", "Función", "Volumen"),
    (9, "Relojes", "Pulso", "Maquinaria", "Resistencia"),
    (10, "Joyería", "Metal", "Piedra", "Kilataje"),

    # --- ALIMENTOS Y MERCADO (20-49) ---
    (20, "Abarrotes", "Contenido", "Marca", "Envase"),
    (21, "Lácteos", "Grasa", "Caducidad", "Tipo"),
    (22, "Vinos y Licores", "Tipo", "Cosecha", "Grados"),
    (23, "Botanas", "Gramos", "Sabor", "Presentación"),
    (24, "Refrescos", "Volumen", "Sabor", "Retornable"),
    (25, "Carnicería", "Corte", "Calidad", "Peso aprox."),
    (26, "Frutas y Verduras", "Variedad", "Calidad", "Origen"),
    (27, "Panadería", "Harina", "Sabor", "Piezas"),
    (28, "Congelados", "Tipo", "Marca", "Temperatura"),
    (29, "Limpieza Hogar", "Aroma", "Litros", "Uso"),
    (30, "Higiene Personal", "Tipo", "Marca", "Tamaño"),
    (31, "Mascotas", "Especie", "Etapa", "Peso Kg"),
    (32, "Desechables", "Material", "Cantidad", "Tipo"),
    (33, "Especias", "Tipo", "Gramos", "Presentación"),

    # --- TECNOLOGÍA (50-69) ---
    (50, "Hardware", "Componente", "Marca", "Interfaz"),
    (51, "Software", "Licencia", "Versión", "Plataforma"),
    (52, "Redes", "Velocidad", "Puertos", "Tipo"),
    (53, "Cómputo", "Procesador", "RAM", "Disco Duro"),
    (54, "Celulares", "Modelo", "Memoria", "Compañía"),
    (55, "Cámaras", "Resolución", "Lente", "Sensor"),
    (56, "Audio", "Conexión", "Potencia", "Tipo"),
    (57, "Videojuegos", "Consola", "Género", "Formato"),
    (58, "Gadgets", "Función", "Batería", "Conexión"),
    (59, "Impresoras", "Tinta", "Conexión", "PPM"),

    # --- FERRETERÍA Y VARIOS (70-89) ---
    (70, "Herramientas", "Tipo", "Potencia", "Marca"),
    (71, "Pintura", "Color", "Base", "Cubeta/Litro"),
    (72, "Eléctrico", "Voltaje", "Calibre", "Tipo"),
    (73, "Plomería", "Medida", "Material", "Presión"),
    (74, "Iluminación", "Watts", "Tono Luz", "Rosca"),
    (75, "Jardinería", "Herramienta", "Uso", "Tamaño"),
    (76, "Tornillería", "Largo", "Grosor", "Rosca"),
    (77, "Cerrajería", "Tipo", "Seguridad", "Material"),
    (78, "Construcción", "Material", "Peso", "Grado"),

    # --- PAPELERÍA Y OFICINA (90-100) ---
    (90, "Papelería", "Tamaño", "Gramaje", "Color"),
    (91, "Escritura", "Punto", "Tinta", "Marca"),
    (92, "Cuadernos", "Hojas", "Rayado", "Pasta"),
    (93, "Dibujo", "Técnica", "Grado", "Marca"),
    (94, "Manualidades", "Material", "Uso", "Color"),
    (95, "Artículos Oficina", "Función", "Marca", "Material"),
    (96, "Regalos", "Ocasión", "Tamaño", "Tipo"),
    (97, "Juguetes", "Edad", "Pilas", "Marca"),
    (98, "Deportes", "Disciplina", "Talla", "Marca"),
    (99, "Instrumentos", "Tipo", "Material", "Afinación"),
    (100, "Varios", "Detalle 1", "Detalle 2", "Detalle 3")]
    cur.executemany("""INSERT OR IGNORE INTO Tipo (idTipo,Tipo,Descripcion1,Descripcion2,Descripcion3) VALUES (?,?,?,?,?);""",(Tipo))
    Contenido_Tipo=[(1,"Chica","Algondo","Azul"),
                    (1,"Mediana","Lino","Amarillo"),
                    (1,"Grande","Cañamo","Cafe"),
                    (1,"Extra Grande","Yute","Rojo"),
                    (1,"","Lana","Negro"),
                    (1,"","Seda","Blanco"),
                    (1,"","Cachemira","Gris"),
                    (1,"","Alpaca","Verde"),
                    (1,"","Piel","Rosa"),
                    (1,"","Poliéster","Morado"),
                    (1,"","Nylon","Naranja"),
                    (1,"","Licra","Beige"),
                    (1,"","Acrílico","Turquesa"),
                    (1,"","Poliamida","Marfil"),
                    (1,"","Viscosa","Vino"),
                    (1,"","Rayón","Fucsia"),
                    (1,"","Acetato","Plata"),
                    (1,"","Modal","Oro"),
                    (1,"","Mezclilla",""),
                    (1,"","Franela",""),
                    (1,"","Polar",""),
                    (2,"Totebag","Piel genuina","Mini"),
                    (2, "Clutch", "Piel sintética/Sintético", "Pequeño"),
                    (2, "Bandolera", "Lona", "Mediano"),
                    (2, "Mochila", "Nylon", "Grande"),
                    (2, "Satchel", "Gamuza", ""),
                    (2, "Hobo", "Charol", ""),
                    (2, "Messenger", "Mezclilla", ""),
                    (2, "Baguette", "Mimbre", ""),
                    (2, "Shopper", "", ""),
                    (2, "Riñonera", "", ""),
                    (2, "Kelly", "", ""),
                    (2, "Doctor Bag", "", ""),
                    (3, "", "", ""),
                    (4, "", "", ""),
                    (5, "", "", ""),
                    (6, "", "", ""),
                    (7, "", "", ""),
                    (8, "", "", ""),
                    (9, "", "", ""),
                    (10, "", "", ""),
                    #(11, "", "", ""),
                    #(12, "", "", ""),
                    #(13, "", "", ""),
                    #(14, "", "", ""),
                    #(15, "", "", ""),
                    #(16, "", "", ""),
                    #(17, "", "", ""),
                    #(18, "", "", ""),
                    (20, "", "", ""),
                    (21, "", "", ""),
                    (22, "", "", ""),
                    (23, "", "", ""),
                    (24, "", "", ""),
                    (25, "", "", ""),
                    (26, "", "", ""),
                    (27, "", "", ""),
                    (28, "", "", ""),
                    (29, "", "", ""),
                    (53,"Intel Core i3-10100","1 GB","120 GB SSD"),
                    (53, "Intel Core i3-12100", "2 GB", "250 GB SSD"),
                    (53, "Intel Core i5-10400", "4 GB", "500 GB SSD"),
                    (53, "Intel Core i5-11400", "8 GB", "500 GB HHD"),
                    (53, "Intel Core i5-12400", "16 GB", "1 TB SSD"),
                    (53, "Intel Core i5-13600K", "32 GB", "1 TB HHD"),
                    (53, "Intel Core i7-10700", "", "2 TB SSD"),
                    (53, "Intel Core i7-12700K", "", "2 TB HHD"),
                    (53, "Intel Core i7-13700K", "", "4 TB SSD"),
                    (53, "Intel Core i9-12900K", "", "6 TB HHD"),
                    (53, "Intel Core i9-13900K", "", "8 TB HHD"),
                    (53, "Intel Core i9-i9-14900K", "", "12 TB HHD"),
                    (53, "AMD Ryzen 3 3200G", "", "16 TB HHD"),
                    (53, "AMD Ryzen 3 4100", "", "20 TB HHD "),
                    (53, "AMD Ryzen 5 3600", "", ""),
                    (54, "", "", ""),
                    (54, "", "", ""),
                    (54, "", "", ""),
                    (54, "", "", ""),
                    (54, "", "", ""),
                    (54,"","",""),
                    (57, "PS1", "Acción", "Digital"),
                    (57, "PS2", "Shooters", "Fisico"),
                    (57, "PS3", "Fighting", ""),
                    (57, "PS4", "Beat 'em up", ""),
                    (57, "PS5", "Aventura", ""),
                    (57, "PSP", "Survival Horror", ""),
                    (57, "PSVITA", "Metroidvania", ""),
                    (57, "XBOX Classic", "RPG", ""),
                    (57, "XBOX 360", "JRPG", ""),
                    (57, "XBOX ONE", "ARPG:", ""),
                    (57, "XBOX SERIE X/S", "MMORPG", ""),
                    (57, "NINTENDO", "Estrategia", ""),
                    (57, "SUPER NINTENDO", "Deportes", ""),
                    (57, "NINTENDO 64", "Carreras", ""),
                    (57, "Game Boy", "Novela Visual", ""),
                    (57, "GAME BOY ADVANCE", "Plataformas", ""),
                    (57, "NINTENDO DS", "Puzzle", ""),
                    (57, "NINTENDO 3DS", "Battle Royale", ""),
                    (57, "GAMECUBE", "Musica", ""),
                    (57, "WII", "", ""),
                    (57, "WII U", "", ""),
                    (57, "SWITCH", "", ""),
                    (57, "SWITCH 2", "", ""),
                    ]
    cur.executemany("""INSERT OR IGNORE INTO Contenido_Tipo (tipo,Descripcion1,Descripcion2,Descripcion3) VALUES (?,?,?,?);""",(Contenido_Tipo))
    con.commit()
if __name__ == '__main__':
    InicializaccioDb()